on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC18F4550
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F4550
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/27a0cd8b42259bfe50fa00ed64f4b768
          gist_title: 19-MPLAB-Ultrasonico-4550.c
          gist_description: Prácticas MPLABX
          github_file: Proyecto/PIC18F4550/19_SR04.X/main.c
          file_encoding: ISO-8859-1
    #PIC18F45K50
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F45K50
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/a644b856562c514232bb7c2df73f878a
          gist_title: 19-MPLAB-Ultrasonico.c
          gist_description: Prácticas MPLABX
          github_file: Proyecto/PIC18F45K50/19_SR04.X/main.c
          file_encoding: ISO-8859-1